
spring:
  application:
    name: gateway-service
  profiles:
    active: dev
  config:
    import: configserver:http://localhost:8071



logging:
  level:
    web: DEBUG
    com.netflix: DEBUG
    org.springframework.web: DEBUG
    edu.iu.c322: DEBUG













